GET http://localhost:8000/products/ HTTP/1.1

###

POST http://localhost:8000/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTg3OTcwLCJpYXQiOjE3NDg1ODc2NzAsImp0aSI6IjVkNGZhNjhjOWNiYjQ5ZTM5MTQ1MzY1Y2Y3MTYwNjMzIiwidXNlcl9pZCI6MX0.JeE75-Sc72aKLhZwh9GEj6-LxKwuW8g_2qae7GfHu7g

{
    "name" : "TV",
    "price" : 300,
    "stock" : 14,
    "description" : "An Amazing TV"
}       

###

GET http://localhost:8000/products/1 HTTP/1.1

###

PUT http://localhost:8000/products/1 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTg3OTcwLCJpYXQiOjE3NDg1ODc2NzAsImp0aSI6IjVkNGZhNjhjOWNiYjQ5ZTM5MTQ1MzY1Y2Y3MTYwNjMzIiwidXNlcl9pZCI6MX0.JeE75-Sc72aKLhZwh9GEj6-LxKwuW8g_2qae7GfHu7g

{
    "name" : "TV",
    "price" : 300,
    "stock" : 14,
    "description" : "An Amazing TV"
}   

###

DELETE http://localhost:8000/products/1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4NTg3OTcwLCJpYXQiOjE3NDg1ODc2NzAsImp0aSI6IjVkNGZhNjhjOWNiYjQ5ZTM5MTQ1MzY1Y2Y3MTYwNjMzIiwidXNlcl9pZCI6MX0.JeE75-Sc72aKLhZwh9GEj6-LxKwuW8g_2qae7GfHu7g

###

POST http://localhost:8000/api/token/ HTTP/1.1
Content-Type: application/json

{
    "username" : "bharath",
    "password" : "djangoreact"
}

###

POST http://localhost:8000/api/token/refresh/ HTTP/1.1
Content-Type: application/json

{
    "refresh" : "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0ODY3NTQwMywiaWF0IjoxNzQ4NTg5MDAzLCJqdGkiOiJhMmI4NWE5Yjc2MjY0YmM5OWUxNjdhNGI4ODBiYzA3ZCIsInVzZXJfaWQiOjF9.AkrzBse3vn5CuNaa_hSFk40USKzJ-8q4B_1nhziEgu4"
}

###

GET http://localhost:8000/orders/46f3dac9-4bb6-41f2-9030-37ddb38acc7e HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODM3NTUzLCJpYXQiOjE3NDg4MzcyNTMsImp0aSI6Ijc4YzY3NGU5MjhlOTQ4NjliNmRiMzE4ODRiZjRiYjE3IiwidXNlcl9pZCI6Mn0.E1vEzIyUvbUMLuMHDkvB7sFMj7Ik6Zu9yKDrWBk_1CA

###

POST http://localhost:8000/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ4ODQ2NjQ0LCJpYXQiOjE3NDg4NDYzNDQsImp0aSI6ImNhOWZkMWEwNjkzZDQzMDlhYjZjODMyMWFhN2I0OGFjIiwidXNlcl9pZCI6Mn0.5eFUMbDNjFpxrB-_cA9VxOrbJoB0BfCJWFyar38L_P0

{
    "status" : "Confirmed",
    "items" : [
        {
            "product":1,
            "quantity":2
        },
        {
            "product":2,
            "quantity":1
        }
    ]
}     

###